import React from "react";
import { Eye, Download, Trash2 } from "lucide-react";
import { FaEllipsisVertical } from "react-icons/fa6";
import type { HRReport } from "./data";

const statusStyles: Record<string, string> = {
  Generated: "bg-green-50 text-green-700",
  Pending: "bg-amber-50 text-amber-700",
  Failed: "bg-red-50 text-red-600",
};

const categoryStyles: Record<string, string> = {
  Attendance: "bg-blue-50 text-blue-700",
  Payroll: "bg-purple-50 text-purple-700",
  Leave: "bg-emerald-50 text-emerald-700",
  Performance: "bg-amber-50 text-amber-700",
  Headcount: "bg-indigo-50 text-indigo-700",
  Onboarding: "bg-cyan-50 text-cyan-700",
};

function ReportActionMenu({
  rowId,
  openMenuId,
  onToggleMenu,
  onView,
  onDownload,
  onDelete,
}: {
  rowId: string;
  openMenuId: string | null;
  onToggleMenu: (id: string | null) => void;
  onView: () => void;
  onDownload: () => void;
  onDelete: () => void;
}) {
  const isOpen = openMenuId === rowId;
  return (
    <div className="relative" onClick={(e) => e.stopPropagation()}>
      <button
        type="button"
        className="h-8 w-8 flex items-center justify-center text-gray-400 hover:text-gray-600 rounded-lg transition-colors"
        onClick={(e) => {
          e.stopPropagation();
          onToggleMenu(isOpen ? null : rowId);
        }}
      >
        <FaEllipsisVertical className="text-base" />
      </button>
      {isOpen && (
        <div className="absolute right-0 top-9 z-20 w-40 rounded-md border border-gray-100 bg-white py-1 shadow-sm">
          <button
            type="button"
            className="w-full px-4 py-2 text-left text-sm text-gray-700 bg-transparent border-none cursor-pointer flex items-center gap-2 hover:bg-gray-50"
            onClick={onView}
          >
            <Eye size={15} /> View
          </button>
          <button
            type="button"
            className="w-full px-4 py-2 text-left text-sm text-gray-700 bg-transparent border-none cursor-pointer flex items-center gap-2 hover:bg-gray-50"
            onClick={onDownload}
          >
            <Download size={15} /> Download
          </button>
          <button
            type="button"
            className="w-full px-4 py-2 text-left text-sm text-red-500 bg-transparent border-none cursor-pointer flex items-center gap-2 hover:bg-gray-50"
            onClick={onDelete}
          >
            <Trash2 size={15} /> Delete
          </button>
        </div>
      )}
    </div>
  );
}

export function createReportColumns({
  openMenuId,
  onToggleMenu,
  onView,
  onDownload,
  onDelete,
}: {
  openMenuId: string | null;
  onToggleMenu: (id: string | null) => void;
  onView: (report: HRReport) => void;
  onDownload: (report: HRReport) => void;
  onDelete: (report: HRReport) => void;
}) {
  return [
    {
      key: "title",
      header: "Report",
      render: (_: unknown, row: HRReport) => (
        <div>
          <p className="text-sm font-medium text-gray-900">{row.title}</p>
          <p className="text-xs text-gray-400">{row.id}</p>
        </div>
      ),
    },
    {
      key: "category",
      header: "Category",
      render: (val: string) => (
        <span
          className={`inline-block px-2.5 py-1 rounded-full text-xs font-medium ${categoryStyles[val] ?? "bg-gray-100 text-gray-600"}`}
        >
          {val}
        </span>
      ),
    },
    {
      key: "period",
      header: "Period",
    },
    {
      key: "generatedDate",
      header: "Date",
      render: (val: string) => (
        <span className="text-sm text-gray-600">
          {new Date(val).toLocaleDateString("en-US", {
            month: "short",
            day: "numeric",
            year: "numeric",
          })}
        </span>
      ),
    },
    {
      key: "generatedBy",
      header: "Generated By",
    },
    {
      key: "status",
      header: "Status",
      render: (val: string) => (
        <span
          className={`inline-block px-2.5 py-1 rounded-full text-xs font-medium ${statusStyles[val] ?? "bg-gray-100 text-gray-600"}`}
        >
          {val}
        </span>
      ),
    },
    {
      key: "actions",
      header: "",
      truncate: false,
      render: (_: unknown, row: HRReport) => (
        <ReportActionMenu
          rowId={row.id}
          openMenuId={openMenuId}
          onToggleMenu={onToggleMenu}
          onView={() => onView(row)}
          onDownload={() => onDownload(row)}
          onDelete={() => onDelete(row)}
        />
      ),
    },
  ];
}
